# Minecraft
minecraft_version=1.19.2
yarn_mappings=1.19.2+build.28
loader_version=0.18.4

# Fabric API
fabric_version=0.77.0+1.19.2

# Mod Properties
mod_version=1.6.2+1.19.2
maven_group=com.neuromuser.worldbordercore
archives_base_name=worldborder-core
cloth_config_version=8.3.134+fabric
modmenu_version=4.2.0-beta.2
